Implement purchase availability
mirumee/saleor-storefront pull request #878
Opened 2020-08-26 10:27 UTC by orzechdev

I want to merge this change because... it adds information if a purchase is not available or when it will be available.

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] Changes are mentioned in the changelog.

### Test Environment Config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-08-27 13:50 UTC, orzechdev commented
Locally e2e tests pass
![Zrzut ekranu 2020-08-27 o 15 17 51](https://user-images.githubusercontent.com/9825562/91450781-f6a7c400-e87c-11ea-8334-d506d5924d44.png)

2020-08-27 16:00 UTC, patrys commented
Task linked: [CU-7enmfm Storefront changes for purchase availability date.](https://app.clickup.com/t/7enmfm)

2020-08-27 19:12 UTC, AlicjaSzu approved these changes

2020-08-31 11:41 UTC, dominik-zeglen requested changes

2020-08-31 11:41 UTC, dominik-zeglen commented on package.json
> +    "moment": "^2.27.0",
No need for `moment`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

2020-09-01 09:40 UTC, orzechdev commented
Do not merge if backend is not merged https://github.com/mirumee/saleor/pull/6060

2020-09-01 14:10 UTC, dominik-zeglen approved these changes

2020-09-01 17:36 UTC, krzysztofwolski approved these changes

2020-09-03 10:40 UTC, merged