Add information about modifying the Storefront
mirumee/saleor-storefront pull request #901
Opened 2020-09-16 10:35 UTC by HarisSpahija

I want to merge this change because it solves #896, #523, #894 and possibly more in the future.

Currently it gives a general idea of how the Storefront is built and where to make adjustments. New users of the `Saleor-Storefront` can get a sense of where to start instead of immediately posting to the issue tracker.

### Screenshots

PR does not affect UI or UX.

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] Changes are mentioned in the changelog.

### Test Environment Config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-21 09:18 UTC, dominik-zeglen approved these changes

2020-09-21 10:35 UTC, orzechdev requested changes
Thank you for your contribution!

Architecture overview in readme sounds to be good, but I'm not sure whether we should have an explanation of how to modify the storefront in readme or maybe it should be in other place.

Although, even If we're going to merge it, I see a few things, which I would recommend to change, to make readme more specific, convincing, and to be absolutely clear about what things are used for.

2020-09-23 18:25 UTC, HarisSpahija commented
I do want to credit user @cyberdemic from the spectrum chat. He created a post [here](https://spectrum.chat/saleor/saleor-storefront/modifying-the-storefront~c1955dbf-a421-4fb6-b99e-937dd2642b23)
I formatted his text to markdown.

2020-09-24 07:01 UTC, orzechdev approved these changes

2020-09-25 11:34 UTC, krzysztofwolski approved these changes

2020-09-25 11:35 UTC, merged