Feature/saleor 1564 Add next.js to the Storefront
mirumee/saleor-storefront pull request #962
Opened 2020-12-05 16:19 UTC by piotrgrundas

* Add next.js to the Storefront 

I want to merge this change because...

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] Changes are mentioned in the changelog.

### Test Environment Config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-12-30 17:19 UTC, matiasmm commented
@piotrgrundas what's the state of this?  is this going to get merged to master soon?

2021-01-03 19:23 UTC, piotrgrundas commented
@matiasmm that's the plan. 
The second PR is waiting to be merged which will finish adding nextjs client only routing to the storefront. Should be merged in the upcoming days.

2021-01-08 16:24 UTC, jwm0 requested changes
Please check the LGTM bot issue and check what's causing the sudden waterfall of TS issues (it looks like a strict TS config is targeting files outside the `src/next` directory)

2021-01-13 12:49 UTC, krzysztofwolski approved these changes
One issue, other that that lookin good

2021-01-13 12:49 UTC, krzysztofwolski commented on .github/workflows/test-env-deploy.yml
> +          envkey_NEXT_PUBLIC_API_URI: ${{ steps.api_uri.outputs.custom_api_uri || 'https://master.staging.saleor.rocks/graphql/' }}
```suggestion
          envkey_NEXT_PUBLIC_API_URI: ${{ steps.api_uri.outputs.custom_api_uri || 'https://master.staging.saleor.rocks/graphql/' }}
```
```suggestion
          envkey_NEXT_PUBLIC_API_URI: ${{ steps.api_uri.outputs.custom_api_uri || 'https://master.staging.saleor.rocks/graphql/' }}
```
```suggestion
          envkey_NEXT_PUBLIC_API_URI: ${{ steps.api_uri.outputs.custom_api_uri || secrets.API_URI }}
```

2021-01-13 15:39 UTC, jwm0 approved these changes

2021-01-13 17:14 UTC, merged