Added variable className
mirumee/saleor-storefront pull request #975
Opened 2021-01-04 18:25 UTC by KierichekPavel

I want to merge this change because...

### Screenshots

### Pull Request Checklist

1. [+] All visible strings are translated with proper context.
1. [+] All data-formatting is locale-aware (dates, numbers, and so on).
1. [+] The changes are tested.
1. [+] The code is documented (docstrings, project documentation).
1. [+] Changes are mentioned in the changelog.

### Test Environment Config

API_URI=https://master.staging.saleor.rocks/graphql/

2021-01-08 08:36 UTC, jwm0 requested changes
Looks good, thanks for the PR. I added some suggestion to make this piece of code more bulletproof.

2021-01-08 08:36 UTC, jwm0 commented on src/components/TextField/index.tsx
> +  const baseClass = `input__field ${className}`;
For an empty `className` we want to trim the whitespaces
```suggestion
  const baseClass = `input__field ${className}`.trim();
```

2021-01-08 08:36 UTC, jwm0 commented on src/components/TextField/index.tsx
> +  className,
We should additionally guard the `className` arg here to avoid passing an `undefined` value to the class name.
```suggestion
  className = "",
```

2021-01-11 09:14 UTC, krzysztofwolski approved these changes

2021-03-26 12:14 UTC, closed without merging