update rich text to allow null values
mirumee/saleor-storefront pull request #996
Opened 2021-02-22 14:41 UTC by mmarkusik

I want to merge this change because...

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] Changes are mentioned in the changelog.

### Test Environment Config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-02-22 14:41 UTC, patrys commented
Task linked: [SALEOR-2270 Editor.js should handle null values in content fields](https://app.clickup.com/t/2549495/SALEOR-2270)

2021-02-23 09:05 UTC, jwm0 requested changes

2021-02-23 09:05 UTC, jwm0 commented on src/@next/components/atoms/RichTextEditorContent/RichTextEditorContent.tsx
> +  if (!jsonData) {
Return statements should come after all hook declarations as this guarantees their call order during render phase:

https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

2021-02-23 09:47 UTC, jwm0 approved these changes

2021-02-23 09:49 UTC, orzechdev approved these changes

2021-02-23 10:01 UTC, merged